### ISSUE TITLE
Possible typo in generated `ukor.properties.yaml`

### ISSUE THREAD

**Issue by nsillik** [willowtreeapps/ukor#58]
The generated `ukor.properties.yaml` file after running `ukor init` looks like it may have a typo:

```yaml
name: roku
version: 0.0.1
buildDir: build
sourceDir: src
defaults:
  falvor: main # Should this be `flavor` instead of `falvor`?
flavors:
  main:
    src:
      - main
```
